
services:
    lmauthors_1:
        image: lmsauthors:latest
        container_name: authors1_in_lms_network
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8090:8080"
        environment:
            SPRING_PROFILES_ACTIVE: instance1,bootstrap
        networks:
            - lms_network
        volumes:
            - "uploaded_files_volume_1:/tmp"

    lmsauthors_2:
        image: lmsauthors:latest
        container_name: authors2_in_lms_network
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8091:8080"
        environment:
            SPRING_PROFILES_ACTIVE: instance2,bootstrap
        networks:
            - lms_network
        volumes:
            - "uploaded_files_volume_2:/tmp"

networks:
    lms_network:
        external: true

volumes:
    uploaded_files_volume_1:
    uploaded_files_volume_2: