
services:
    lmsgenres_1:
        image: lmsgenres:latest
        container_name: genres1_in_lms_network
        build:
            context: ..
            dockerfile: Dockerfile
        ports:
            - "8087:8080"
        environment:
            SPRING_PROFILES_ACTIVE: instance1,bootstrap
        networks:
            - lms_network
        volumes:
            - "uploaded_files_volume_1:/tmp"

    lmsgenres_2:
        image: lmsgenres:latest
        container_name: genres2_in_lms_network
        build:
            context: ..
            dockerfile: Dockerfile
        ports:
            - "8088:8080"
        environment:
            SPRING_PROFILES_ACTIVE: instance2,bootstrap
        networks:
            - lms_network
        volumes:
            - "uploaded_files_volume_2:/tmp"

networks:
    lms_network:
        external: true

volumes:
    uploaded_files_volume_1:
    uploaded_files_volume_2: